[package]
name = "bzip"
version = "0.1.0"
authors = ["Felipe Bemfica <felipe.m.p.bemfica@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
